### ISSUE TITLE
Crash when opening world

### ISSUE THREAD

**Issue by ItsChase7** [MundM2007/Ultimate-Progression-Sky#21]
I just created my world havent seen it but crash everytime I try to open it 
[crash-2023-06-04_15.04.18-server.txt](https://github.com/MundM2007/Ultimate-Progression-Sky/files/11646439/crash-2023-06-04_15.04.18-server.txt)

**Comment by PythonSharpPlus** [comment]
I'm not sure how to read crash reports so I may be wrong but when this happens to me it is because I am doing things such as clicking or trying to go to separate tabs when loading into the world the next time you open the world try just opening it and waiting for it to load in not doing anything on your computer It will probably take a few minutes to load in or try adding extra ram allocation to your game.

**Comment by MundM2007** [comment]
Are you trying to start a Server? If so Set max-tick-time to -1 in Server.properties

**Comment by ItsChase7** [comment]
> Are you trying to start a Server? If so Set max-tick-time to -1 in Server.properties
No this is a singleplayer, I think the problem was that I had optifine in there. Do you guys know of any optifine that works with the pack because it is a pretty big one?

**Comment by MundM2007** [comment]
Yeah that explains it, don't use optifine for any packs. It will most likely crash, with no way to fix because optifine is closed source. (This is the opinion of mod devs)
