### ISSUE TITLE
[CRASH] Optifine

### ISSUE THREAD

**Issue by SoftGuardian** [MundM2007/Ultimate-Progression-Sky#26]
What mods conflict with optifine on the launch other than Embeddium and it's counter parts (which I removed all of them)
I have to play the modpack with optifine, no debates, there's just one mod that i'm sure is causing the game to crash on launch which removing it would fix it usually.

- Modpack version: 1.2.4
- Server?: no

**Crash Report / log**

[latest.log](https://github.com/MundM2007/Ultimate-Progression-Sky/files/14394124/latest.log)

**Comment by MundM2007** [comment]
No Support for optifine will be givrn, all features from optifine are possible to achieve with other mods, Like shaders with Oculus. Optifine worsens Performance and is completely incompatible with almost every other Mod to some extent. It's Just Bad, because it's closed source, so Nobody can add compat to it.

**Comment by SoftGuardian** [comment]
yes I did try to remove it since I did take a look at the logs. But instead of crashing right away at launch, it crashes while loading the mods with the mojang screen.
[2024-02-24-3.log](https://github.com/MundM2007/Ultimate-Progression-Sky/files/14394587/2024-02-24-3.log)

**Comment by MundM2007** [comment]
Randompatches seems to be the issue

**Comment by MundM2007** [comment]
Though why do you really need optifine, there's Like No reason
